### ISSUE TITLE
Add documentation to build models from source

### ISSUE THREAD

**Issue by cherryland** [robertmarshii/OpenMeter-A-Secure-Password-Meter-Using-Tensorflow#1]
Please add additional documentation to build models from source. 

The default Tensor flow model is useless for Non-English languages. I would like to provide additional models for Asian languages, eg. Chinese, Korean and Japanese.

**Comment by robertmarshii** [comment]
I am still waiting for my paper to be published, once this happens those details will be shared. Thanks for your interest in this project.
